# need to use sudo-enabled containers for additional RAM
dist: trusty
sudo: required
language: java
jdk: oraclejdk9
python:
  - "3.6"
cache:
  directories:
    - "native/javascript/node_modules"
install:
  - cd native/javascript
  - npm install
  - cd ../..
before_script:
  - export WYVERN_HOME="$(pwd)"
  - export _JAVA_OPTIONS="-Xmx6144m -Xms512m -XX:+UseParallelGC"
script:
  - cd tools
  - travis_wait ant test
  - cd ../backend
  - ./bootstrap.sh travis
  - ./test.sh
notifications:
  email:
    recipients:
      - jonathan.aldrich@cs.cmu.edu
